### ISSUE TITLE
Delegate Vote component should allow ENS names

### ISSUE THREAD

**Issue by adamgall** [fractal-framework/fractal-interface#155]
Not sure how we're gonna test... Are the ENS contracts deployed to testnets? If so, does `ethers.js` support those testnet ENS deployments?

**Comment by Da-Colon** [comment]
currently field validation is handled outside of the input with it only receiving an `errorMessage` prop `string | undefined`. Would just need to add some logic to use 'checkAddress' method. since deleteVote isn't a element that is mapped, probably could use the `useAddress` hook instead of the method for like the `useSearchDao` is currently using it.

**Comment by adamgall** [comment]
@Da-Colon yes sir whatever you say sir
