### ISSUE TITLE
Update "Active" proposal label style

### ISSUE THREAD

**Issue by sethhrbek** [fractal-framework/fractal-interface#213]
The "Active" label should use the main orange/yellow color that is used throughout the app.

Currently "Active" is gray which makes it looks like the proposal is inactive.

![image](https://user-images.githubusercontent.com/43755993/167032369-f4bbdc84-8322-4a47-b5dc-e41cd63ea9c7.png)

**Comment by Da-Colon** [comment]
@dannydecent thoughts?

**Comment by dannydecent** [comment]
I agree with both of you. @sethhrbek comment here and a previous convo with @Da-Colon 

the active tag here needs restyling because it looks too much like a button with any current design pattern/treatment. 

quick fix option (without mocks) make it an oval, not rounded corners and make it yellow.

**Comment by adamgall** [comment]
First off:

* There is some code that allows the status stamp icon thing to be yellow, but it's never being matched...
* Because it's looking for a status string of `"Open"`...
* But the status string is never `"Open"`
* Probably mean to be matching for `"Active"`

I took a shot at making the pills looks more like pills, and making sure that Active proposals actually got a non-disabled looking pill

<img width="760" alt="Screen Shot 2022-05-06 at 8 53 52 PM" src="https://user-images.githubusercontent.com/706929/167231469-5e53c567-fec4-4e34-85ae-66a817e2adfe.png">

@dannydecent what do u think?

**Comment by adamgall** [comment]
Another issue here is that we're doing this freeform string matching, which OBVIOUSLY is hacky and doesn't work well, because we ran into this very situation.

The proposal data's `status` property should be either an explicitly defined list of strings (not a freeform string), or a Typescript enum.

**Comment by Da-Colon** [comment]
Played around in figma. was thinking we could use more of this real estate. I definitely like the more oval 'pill'. any thoughts on any of these changes ? 

![image](https://user-images.githubusercontent.com/38386583/167279197-e95ca573-1186-4ce8-828d-4f149c2b1bc3.png)
