### ISSUE TITLE
2nd header styling / features for proposals

### ISSUE THREAD

**Issue by christopherdancy** [fractal-framework/fractal-interface#65]
1. User should be able to view proposals # and create a proposal on the summary page. 
2. On proposal detail page - User should be able to see proposal # and description
<img width="946" alt="image" src="https://user-images.githubusercontent.com/69045872/165565246-4d8a7307-8613-4656-8175-e0e9a8f66b6e.png">

**Comment by adamgall** [comment]
1a. On the DAO summary page, we're already showing the list of proposal cards, which include numbers.

1b. Agreed that we need to put a button/link the DAO summary page to take user to the New Proposal page. I believe the designs for this have the button in the breadcrumb bar... which seems random.

2. the proposal detail page does show proposal number and description.

overall, i'm confused about what the goal of this issue is for

**Comment by christopherdancy** [comment]
The goal is to get the codebase to look like the figma docs. Should we speak with design first?

**Comment by adamgall** [comment]
It's not clear to me how this issues title, the two description points, and screenshot, are related.

Can you please provide some more context? What is the scope of the visual work you'd like to see changed as a result of this issue?

**Comment by adamgall** [comment]
This issue seems to be stale, design team is content with current breadcrumb
